image: artifactory.wbaa.pl.ing.net/registry/python:3.7

stages:
  - lint
  - static
  - test
  - notebooks
  - test-backward-compatibility

lint:
  stage: lint
  tags: [docker-tag]
  script:
    - pip install flake8
    - flake8

static:
  stage: static
  tags: [docker-tag]
  script:
    - pip install mypy pandas-stubs
    - mypy --ignore-missing-imports ./strictly_typed_pandas ./tests

test:
  stage: test
  tags: [docker-tag]
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - coverage run -m pytest --typeguard-packages=strictly_typed_pandas,tests
    - coverage report -m

notebooks:
  stage: notebooks
  tags: [docker-tag]
  script:
    - pip install -r requirements.txt
    - pip install papermill jupyter
    - papermill notebooks/getting_started.ipynb output.json -k python3
    - papermill notebooks/advanced.ipynb output.json -k python3
    - papermill notebooks/deepdive_into_dtypes.ipynb output.json -k python3

test-backward-compatibility:
  stage: test-backward-compatibility
  tags: [docker-tag]
  image: artifactory.wbaa.pl.ing.net/registry/python:3.6
  script:
    - pip install -r requirements.txt
    - pip install pytest pandas==0.23
    - pytest --typeguard-packages=strictly_typed_pandas,tests
