name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run notebooks
        run: |
           papermill docs/source/getting_started.ipynb output.json -k python3
           papermill docs/source/advanced.ipynb output.json -k python3
           papermill docs/source/deepdive_into_dtypes.ipynb output.json -k python3
